<a href="https://colab.research.google.com/github/somyamangla/Somya/blob/main/ASSIGNMENT_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [9]:
d = {'Name':pd.Series(["Tom","James", "Ricky","Vin","Steve","Smith","Jack"]), 'Age':pd.Series([25,26,25,23,30,29,23]),
'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

In [13]:
for i in d :
  print(d[i].shape)

(7,)
(7,)
(7,)


In [14]:
for i in d :
  print(d[i].size)

7
7
7


In [15]:
for i in d :
  print(d[i].head())

0      Tom
1    James
2    Ricky
3      Vin
4    Steve
dtype: object
0    25
1    26
2    25
3    23
4    30
dtype: int64
0    4.23
1    3.24
2    3.98
3    2.56
4    3.20
dtype: float64


In [16]:
for i in d :
  print(d[i].tail())

2    Ricky
3      Vin
4    Steve
5    Smith
6     Jack
dtype: object
2    25
3    23
4    30
5    29
6    23
dtype: int64
2    3.98
3    2.56
4    3.20
5    4.60
6    3.80
dtype: float64


In [11]:
for i in d :
    print(i, d[i].dtype)

Name object
Age int64
Rating float64


In [19]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
            'Rank': [1,2,2,3,3,4,1,1,2,4,1,2],
            'Year': [2014,2015,2014 ,2015, 2014, 2015 ,2016,2017,2016,2014,2015,2017],
            'Points': [876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
print(df)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690


In [21]:
print(df.groupby('Team'))


In [22]:
print(df.groupby('Team').groups)

{'Devils': [2, 3], 'Kings': [4, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10], 'kings': [5]}


In [23]:
import numpy as np

In [24]:
a = np.array([10,20,30])
b=np.array([3,5,7])

In [25]:
np.power(a,b)

array([       1000,     3200000, 21870000000])

In [26]:
np.mod(a,b)

array([1, 0, 2])

In [27]:
np.remainder(a,b)

array([1, 0, 2])